// saga
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CREATE_NEW_COCKTAIL = 'CREATE_NEW_COCKTAIL';
export const GET_COCKTAILS = 'GET_COCKTAILS';
export const GET_USERS_COCKTAILS = 'GET_USERS_COCKTAILS';
export const GET_COCKTAIL_INFO = 'GET_COCKTAIL_INFO';
export const PUBLISH_COCKTAIL = 'PUBLISH_COCKTAIL';
export const DELETE_COCKTAIL = 'DELETE_COCKTAIL';
export const SET_RATING_COCKTAIL = 'SET_RATING_COCKTAIL';

// redux

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const CREATE_NEW_COCKTAIL_SUCCESS = 'CREATE_NEW_COCKTAIL_SUCCESS';
export const CREATE_NEW_COCKTAIL_ERROR = 'CREATE_NEW_COCKTAIL_ERROR';

export const GET_COCKTAILS_SUCCESS = 'GET_COCKTAILS_SUCCESS';
export const GET_COCKTAILS_ERROR = 'GET_COCKTAILS_ERROR';
export const GET_COCKTAIL_INFO_SUCCESS = 'GET_COCKTAIL_INFO_SUCCESS';
export const GET_COCKTAIL_INFO_ERROR = 'GET_COCKTAIL_INFO_ERROR';

export const PUBLISH_COCKTAIL_SUCCESS = 'PUBLISH_COCKTAIL_SUCCESS';
export const PUBLISH_COCKTAIL_ERROR = 'PUBLISH_COCKTAIL_ERROR';
export const DELETE_COCKTAIL_SUCCESS = 'DELETE_COCKTAIL_SUCCESS';
export const DELETE_COCKTAIL_ERROR = 'DELETE_COCKTAIL_ERROR';
export const SET_RATING_COCKTAIL_SUCCESS = 'SET_RETING_COCKTAIL_SUCCESS';
export const SET_RATING_COCKTAIL_ERROR = 'SET_RATING_COCKTAIL_ERROR';